import type { Metadata } from "next";
import { Providers } from "./providers";
import Head from "next/head";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./components/header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
        <meta
          property="og:title"
          content="C.B.D.B.'s - The Comic-Book Database"
          key="title"
        />
      </Head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <Header />
          <div className="font-sans grid grid-rows-[20px_1fr_20px] justify-items-left min-h-screen pl-5 pr-5 pb-20 pt-10 sm:p-5">
            <main className="flex flex-col gap-[32px] row-start-1 items-center sm:items-start">
              {children}
            </main>
          </div>
        </Providers>
      </body>
    </html>
  );
}
